openapi: 3.0.0
info:
  title: SnowPasteDeliveryAPI
  version: '1.0'
  description: An API for a food delivery application. For NEU CS5500 project.
servers:
  - url: 'http://localhost:5000'
paths:
  /restaurants:
    get:
      summary: get all restaurants
      tags:
        - restaurants
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  restaurantName:
                    type: string
      operationId: get-restaurants
      description: get all restaurants in the database. Here.
    parameters: []
  '/orders/{orderId}':
    get:
      summary: get an order with orderId
      tags:
        - orders
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: getOrder
      description: get an order with orderId
    parameters:
      - schema:
          type: string
          format: uuid
        name: orderId
        in: path
        description: Id of order to get
        required: true
  '/restaurants/{restaurantId}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: restaurantId
        in: path
        required: true
        description: Id of restaurant to get
    get:
      summary: get a restaurant with restaurantId
      tags:
        - restaurants
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: getRestaurant
      description: get a restaurant with restaurantId
components:
  schemas: {}
  securitySchemes:
    app_id:
      name: appid
      type: apiKey
      in: query
tags:
  - name: restaurants
  - name: orders
